services:
    texteller:
        build: ./texteller
        image: texteller
        shm_size: 3.24g
        ports:
            - "8000:8000"
    feedback:
        build: ./feedback
        image: hmer-feedback
        ports:
            - "3100:3100"
        volumes:
            - ./feedback/data:/app/data
